# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lee McKinnon
email: hello@leemckinnon.com
description: > # this means to ignore newlines until "baseurl:"
  I'm currently the Director of Software Engineering at [Ledgex](http://ledgex.com) as well as a full-stack Software Engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://leemckinnon.com" # the base hostname & protocol for your site
twitter_username: leemak
github_username:  leemac

# Build settings
markdown: kramdown

highlighter: rogue
